sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t brunobento/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true brunobento/docker-react npm run test